"""empty message

Revision ID: 01b75698b5b8
Revises: 25ad95f801de
Create Date: 2019-03-14 20:31:05.156299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b75698b5b8'
down_revision = '25ad95f801de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_admin', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('tb_admin', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('tb_admin', sa.Column('sex', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_admin', 'sex')
    op.drop_column('tb_admin', 'phone')
    op.drop_column('tb_admin', 'age')
    # ### end Alembic commands ###
