"""empty message

Revision ID: 25ad95f801de
Revises: 5a293e1dc753
Create Date: 2019-03-10 18:01:35.253973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ad95f801de'
down_revision = '5a293e1dc753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_menu', sa.Column('image_url_1', sa.String(length=128), nullable=True))
    op.add_column('tb_menu', sa.Column('image_url_2', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_tb_menu_image_url_1'), 'tb_menu', ['image_url_1'], unique=False)
    op.create_index(op.f('ix_tb_menu_image_url_2'), 'tb_menu', ['image_url_2'], unique=False)
    op.drop_index('ix_tb_menu_image_url', table_name='tb_menu')
    op.drop_column('tb_menu', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_menu', sa.Column('image_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('ix_tb_menu_image_url', 'tb_menu', ['image_url'], unique=False)
    op.drop_index(op.f('ix_tb_menu_image_url_2'), table_name='tb_menu')
    op.drop_index(op.f('ix_tb_menu_image_url_1'), table_name='tb_menu')
    op.drop_column('tb_menu', 'image_url_2')
    op.drop_column('tb_menu', 'image_url_1')
    # ### end Alembic commands ###
