"""empty message

Revision ID: 5a293e1dc753
Revises: 788a53b697f4
Create Date: 2019-03-10 17:33:18.275204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a293e1dc753'
down_revision = '788a53b697f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_menu', sa.Column('image_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_tb_menu_image_name'), 'tb_menu', ['image_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_menu_image_name'), table_name='tb_menu')
    op.drop_column('tb_menu', 'image_name')
    # ### end Alembic commands ###
