"""empty message

Revision ID: 60213bd295e8
Revises: 775db2d921f9
Create Date: 2019-03-23 02:37:52.846931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60213bd295e8'
down_revision = '775db2d921f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('user_open_id', sa.String(length=1024), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_user_image_url'), 'tb_user', ['image_url'], unique=False)
    op.create_index(op.f('ix_tb_user_name'), 'tb_user', ['name'], unique=False)
    op.create_index(op.f('ix_tb_user_user_open_id'), 'tb_user', ['user_open_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_user_open_id'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_image_url'), table_name='tb_user')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
