"""empty message

Revision ID: 775db2d921f9
Revises: 01b75698b5b8
Create Date: 2019-03-15 16:00:18.569155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775db2d921f9'
down_revision = '01b75698b5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_admin', sa.Column('image_name', sa.String(length=128), nullable=True))
    op.add_column('tb_admin', sa.Column('image_url_1', sa.String(length=128), nullable=True))
    op.add_column('tb_admin', sa.Column('image_url_2', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_tb_admin_image_name'), 'tb_admin', ['image_name'], unique=False)
    op.create_index(op.f('ix_tb_admin_image_url_1'), 'tb_admin', ['image_url_1'], unique=False)
    op.create_index(op.f('ix_tb_admin_image_url_2'), 'tb_admin', ['image_url_2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_admin_image_url_2'), table_name='tb_admin')
    op.drop_index(op.f('ix_tb_admin_image_url_1'), table_name='tb_admin')
    op.drop_index(op.f('ix_tb_admin_image_name'), table_name='tb_admin')
    op.drop_column('tb_admin', 'image_url_2')
    op.drop_column('tb_admin', 'image_url_1')
    op.drop_column('tb_admin', 'image_name')
    # ### end Alembic commands ###
