"""empty message

Revision ID: 788a53b697f4
Revises: a44c1ea63044
Create Date: 2019-03-10 01:41:55.269033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788a53b697f4'
down_revision = 'a44c1ea63044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type_name', sa.String(length=64), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('launch_date', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('is_grounding', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_menu_image_url'), 'tb_menu', ['image_url'], unique=False)
    op.create_index(op.f('ix_tb_menu_name'), 'tb_menu', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_menu_name'), table_name='tb_menu')
    op.drop_index(op.f('ix_tb_menu_image_url'), table_name='tb_menu')
    op.drop_table('tb_menu')
    # ### end Alembic commands ###
