"""empty message

Revision ID: a44c1ea63044
Revises: e2d6d86773b4
Create Date: 2019-03-06 23:50:49.538698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44c1ea63044'
down_revision = 'e2d6d86773b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_admin', sa.Column('is_super', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_admin', 'is_super')
    # ### end Alembic commands ###
