"""empty message

Revision ID: b971bdd3968a
Revises: e3a4d4b50289
Create Date: 2019-03-25 05:16:09.362044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b971bdd3968a'
down_revision = 'e3a4d4b50289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('order_address', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_order', 'order_address')
    # ### end Alembic commands ###
